import React, { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { HashRouter, Link, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import './styles.css'
import { profile } from './data/profile'
import projects from './data/projects'
import certifications from './data/certifications'
import { formspreeEndpoint } from './config/contact'

const Icon = ({ name, size = 20 }) => {
  const paths = {
    github: <path d="M12 2C6.48 2 2 6.59 2 12.25c0 4.52 2.87 8.35 6.84 9.7.5.1.68-.22.68-.49v-1.89c-2.78.62-3.37-1.22-3.37-1.22-.45-1.19-1.11-1.5-1.11-1.5-.91-.64.07-.63.07-.63 1 .07 1.54 1.07 1.54 1.07.9 1.57 2.35 1.12 2.92.86.09-.67.35-1.12.64-1.38-2.22-.26-4.56-1.15-4.56-5.11 0-1.13.39-2.05 1.04-2.78-.1-.26-.45-1.32.1-2.75 0 0 .85-.28 2.75 1.06A9.34 9.34 0 0 1 12 6.86c.85 0 1.7.12 2.5.35 1.9-1.34 2.75-1.06 2.75-1.06.55 1.43.2 2.49.1 2.75.65.73 1.04 1.65 1.04 2.78 0 3.97-2.34 4.85-4.57 5.1.36.33.68.97.68 1.96v2.91c0 .27.18.59.69.49A10.27 10.27 0 0 0 22 12.25C22 6.59 17.52 2 12 2Z" />,
    linkedin: <path d="M6.5 8.5H3.25V21H6.5V8.5ZM4.88 3A1.88 1.88 0 1 0 4.9 6.75 1.88 1.88 0 0 0 4.88 3ZM20.75 13.83c0-3.77-2-5.52-4.68-5.52a4.06 4.06 0 0 0-3.66 2.01h-.04V8.5H9.25V21h3.25v-6.19c0-1.63.3-3.21 2.27-3.21 1.94 0 1.96 1.84 1.96 3.32V21H20v-7.17h.75Z" />,
    arrow: <path d="M5 12h14M13 6l6 6-6 6" />,
    external: <><path d="M14 3h7v7" /><path d="M10 14 21 3" /><path d="M21 14v5a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5" /></>,
    location: <><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z" /><circle cx="12" cy="10" r="2.5" /></>,
    mail: <><rect x="3" y="5" width="18" height="14" rx="2" /><path d="m3 7 9 6 9-6" /></>,
  }
  return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill={name === 'github' || name === 'linkedin' ? 'currentColor' : 'none'} stroke={name === 'github' || name === 'linkedin' ? 'none' : 'currentColor'} strokeWidth="1.8" aria-hidden="true">{paths[name]}</svg>
}

function scrollToSection(id) {
  window.setTimeout(() => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 50)
}

function Header() {
  const [open, setOpen] = useState(false)
  const navigate = useNavigate()
  const location = useLocation()
  const go = (id) => { setOpen(false); if (location.pathname !== '/') navigate('/'); scrollToSection(id) }
  const links = [['Home', 'home'], ['About', 'about'], ['Skills', 'skills'], ['Projects', 'projects'], ['Certifications', 'certifications'], ['Education', 'education'], ['Contact', 'contact']]
  return <header className="site-header"><nav className="nav wrap" aria-label="Main navigation">
    <Link className="brand" to="/" onClick={() => { setOpen(false); scrollToSection('home') }}>AS<span>.</span></Link>
    <button className="menu-button" aria-label="Toggle navigation" aria-expanded={open} onClick={() => setOpen(!open)}><span /><span /><span /></button>
    <div className={`nav-links ${open ? 'open' : ''}`}>{links.map(([label, id]) => <button key={id} onClick={() => id === 'projects' ? (setOpen(false), navigate('/projects')) : id === 'certifications' ? (setOpen(false), navigate('/certifications')) : go(id)}>{label}</button>)}<a className="nav-resume" href={profile.resumeUrl} target="_blank" rel="noreferrer">Resume <Icon name="external" size={14} /></a></div>
  </nav></header>
}

function SectionTitle({ eyebrow, title, text }) { return <div className="section-heading"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{text && <p>{text}</p>}</div> }
function Tags({ items }) { return <div className="tags">{items.map(item => <span key={item}>{item}</span>)}</div> }
function ProjectCard({ project }) { return <article className="project-card"><div className="card-top"><span className="project-mark">{project.title.slice(0, 2).toUpperCase()}</span><span className="card-label">Project</span></div><h3>{project.title}</h3><p>{project.shortDescription}</p><Tags items={project.technologies} /><Link className="text-link" to={`/projects/${project.slug}`}>Explore project <Icon name="arrow" size={17} /></Link></article> }

function Hero() { return <section id="home" className="hero wrap"><div className="hero-copy"><p className="eyebrow">Hello, I’m</p><h1>Arunprakash <em>S</em></h1><p className="hero-title">{profile.title}</p><p className="hero-summary">I work with Python, SQL, analytics, visualization, and machine learning to turn data into practical, meaningful solutions.</p><p className="location"><Icon name="location" size={18} />{profile.location}</p><div className="actions"><button className="button primary" onClick={() => scrollToSection('featured-projects')}>View Projects <Icon name="arrow" size={18} /></button><a className="button secondary" href={profile.resumeUrl} target="_blank" rel="noreferrer">Resume <Icon name="external" size={17} /></a><button className="button ghost" onClick={() => scrollToSection('contact')}>Contact Me</button></div><div className="socials"><a href={profile.github} target="_blank" rel="noreferrer" aria-label="GitHub"><Icon name="github" /></a><a href={profile.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn"><Icon name="linkedin" /></a></div></div><div className="portrait-wrap"><div className="portrait-frame"><img src={`${import.meta.env.BASE_URL}profile.jpeg`} alt="Arunprakash S" /></div><span className="portrait-note">Data • Analysis • Insights</span></div></section> }

const skills = [
  ['Programming & Query', ['Python', 'SQL']], ['Data Analysis', ['NumPy', 'Pandas']], ['Data Visualization & Business Intelligence', ['Matplotlib', 'Seaborn', 'Power BI', 'Tableau']], ['Machine Learning', ['Machine Learning']], ['Databases', ['MySQL', 'MongoDB', 'ChromaDB']], ['AI / GenAI Technologies', ['LLMs', 'RAG', 'LangChain', 'LangGraph', 'MCP', 'Ollama', 'Embeddings', 'Vector Databases']], ['Cloud', ['AWS', 'Microsoft Azure', 'Google Cloud (GCP)']], ['Developer Tools', ['Git', 'GitHub', 'Linux (Ubuntu)']],
]
function AboutSkills() { return <><section id="about" className="section wrap about"><SectionTitle eyebrow="About me" title="A data-first approach to solving practical problems." /><div className="about-copy"><p>I’m an MCA graduate and aspiring Data Professional focused on Python, SQL, data analysis, data visualization, and machine learning. I enjoy working with data to uncover meaningful insights and build practical, data-driven solutions.</p><p>Alongside this data foundation, I have familiarity with modern AI application technologies including LLMs, RAG, LangChain, LangGraph, MCP, Ollama, embeddings, and vector databases.</p></div></section><section id="skills" className="section section-alt"><div className="wrap"><SectionTitle eyebrow="Capabilities" title="Skills and technologies" text="A focused toolkit for data work, visualization, and modern application development." /><div className="skills-grid">{skills.map(([title, items]) => <article className="skill-card" key={title}><h3>{title}</h3><Tags items={items} /></article>)}</div></div></section></> }
function FeaturedProjects() { return <section id="featured-projects" className="section wrap"><div className="split-heading"><SectionTitle eyebrow="Selected work" title="Featured projects" text="A selection of projects spanning data workflows, application development, and retrieval-based systems." /><Link to="/projects" className="text-link all-link">All projects <Icon name="arrow" size={17} /></Link></div><div className="projects-grid">{projects.map(project => <ProjectCard project={project} key={project.slug} />)}</div></section> }
function Education() { const items = [['Master of Computer Applications (MCA)', 'Jain (Deemed-to-be University), Bengaluru', '2024 – 2026', 'CGPA: 7.3'], ['B.Sc. (Information Technology)', 'Kongu Arts and Science College, Erode', '2021 – 2024', 'CGPA: 7.3']]; return <section id="education" className="section section-alt"><div className="wrap"><SectionTitle eyebrow="Education" title="Academic background" /><div className="timeline">{items.map(([degree, school, period, cgpa]) => <article className="education-card" key={degree}><span className="timeline-dot" /><p className="period">{period}</p><h3>{degree}</h3><p>{school}</p><span className="cgpa">{cgpa}</span></article>)}</div></div></section> }

function Contact() { const [form, setForm] = useState({ name: '', email: '', mobile: '', message: '' }); const [state, setState] = useState(''); const endpoint = import.meta.env.VITE_FORMSPREE_ENDPOINT || formspreeEndpoint; const submit = async (e) => { e.preventDefault(); setState('sending'); try { const res = await fetch(endpoint, { method: 'POST', headers: { Accept: 'application/json', 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (!res.ok) throw new Error(); setState('success'); setForm({ name: '', email: '', mobile: '', message: '' }) } catch { setState('error') } }; return <section id="contact" className="section wrap"><SectionTitle eyebrow="Get in touch" title="Let’s start a conversation." text="Feel free to reach out about data projects, opportunities, or a professional conversation." /><div className="contact-grid"><div className="contact-details"><a href={`mailto:${profile.email}`}><Icon name="mail" /><span><small>Email</small>{profile.email}</span></a><a href={`tel:${profile.mobile}`}><Icon name="location" /><span><small>Mobile</small>{profile.mobile}</span></a><p><Icon name="location" /><span><small>Location</small>{profile.location}</span></p><div className="contact-social"><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn <Icon name="external" size={15} /></a><a href={profile.github} target="_blank" rel="noreferrer">GitHub <Icon name="external" size={15} /></a></div></div><form className="contact-form" onSubmit={submit}><label>Name *<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Email *<input type="email" required value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Mobile Number *<input type="tel" required value={form.mobile} onChange={e => setForm({ ...form, mobile: e.target.value })} /></label><label>Message *<textarea required rows="5" value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} /></label><button className="button primary" disabled={state === 'sending'}>{state === 'sending' ? 'Sending…' : 'Send Message'} <Icon name="arrow" size={18} /></button>{state === 'success' && <p className="form-message success">Thanks! Your message has been sent successfully.</p>}{state === 'error' && <p className="form-message error">Message could not be sent. Please try again or email directly.</p>}</form></div></section> }
function Home() { return <><Hero /><AboutSkills /><FeaturedProjects /><Education /><Contact /></> }
function ProjectsPage() { return <main className="page wrap"><SectionTitle eyebrow="Portfolio" title="Projects" text="Data, analytics, and application projects built to explore practical problems." /><div className="projects-grid">{projects.map(p => <ProjectCard project={p} key={p.slug} />)}</div></main> }
function ProjectDetail() { const { slug } = useParams(); const project = projects.find(p => p.slug === slug); if (!project) return <main className="page wrap not-found"><h1>Project not found</h1><Link className="button secondary" to="/projects">Back to projects</Link></main>; return <main className="page wrap detail"><Link className="back" to="/projects">← All projects</Link><p className="eyebrow">Project case study</p><h1>{project.title}</h1><p className="lead">{project.shortDescription}</p><Tags items={project.technologies} /><div className="detail-grid"><div><h2>Overview</h2><p>{project.description}</p></div><div className="feature-panel"><h2>Highlights</h2><ul>{project.features.map(f => <li key={f}>{f}</li>)}</ul></div></div><div className="actions"><a className="button primary" href={project.github} target="_blank" rel="noreferrer">Source Code <Icon name="external" size={17} /></a>{project.demo ? <a className="button secondary" href={project.demo} target="_blank" rel="noreferrer">Live Demo <Icon name="external" size={17} /></a> : <button className="button disabled" disabled>Live Demo — Coming Soon</button>}</div></main> }
function CertificationsPage() { return <main className="page wrap"><SectionTitle eyebrow="Learning" title="Certifications" text="A record of formal learning across data, databases, cloud, and AI product development." /><div className="cert-grid">{certifications.map(c => <article className="cert-card" key={c.credentialUrl}><span className="card-label">{c.year}</span><h3>{c.name}</h3><p>{c.issuer}</p><a className="text-link" href={c.credentialUrl} target="_blank" rel="noreferrer">View Credential <Icon name="external" size={16} /></a></article>)}</div></main> }
function Footer() { return <footer><div className="wrap footer-inner"><div><strong>{profile.name}</strong><span>{profile.title}</span></div><div><a href={profile.github} target="_blank" rel="noreferrer">GitHub</a><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn</a><a href={`mailto:${profile.email}`}>Email</a></div><small>© {new Date().getFullYear()} {profile.name}</small></div></footer> }
function App() { return <><Header /><Routes><Route path="/" element={<Home />} /><Route path="/projects" element={<ProjectsPage />} /><Route path="/projects/:slug" element={<ProjectDetail />} /><Route path="/certifications" element={<CertificationsPage />} /><Route path="*" element={<Home />} /></Routes><Footer /></> }
createRoot(document.getElementById('root')).render(<React.StrictMode><HashRouter><App /></HashRouter></React.StrictMode>)
